### ISSUE TITLE
REPL for erde

### ISSUE THREAD

**Issue by zaxebo1** [erde-lang/erde#1]
Just like lua has its own REPL(read-eval-print-loop), as in example below:

bash%  lua
Lua 5.4.2  Copyright (C) 1994-2020 Lua.org, PUC-Rio

> print("hi")
hi

> function f1(x)
>> print("hi")
>> end
 
> f1()
hi
 
-----------------
**In the same way kindly please implement REPL for erde**

**Comment by bsuth** [comment]
Already planned for the future! 🎉

**Comment by bsuth** [comment]
closed by https://github.com/erde-lang/erde/pull/3
