### ISSUE TITLE
optionally Type hints on variables

### ISSUE THREAD

**Issue by zaxebo1** [erde-lang/erde#2]
One may optionally type hint the variables, which will always be ignored

function sum(a : number, b: number) {
  return a + b
}

Here number will be ignored by erde compiler (just like python3 compiler ignores the type hints). but some may either visually check later or implement a separate typechecker , which will validate the types - just as it is done in python3 ( see https://docs.python.org/3/library/typing.html )

**Comment by zaxebo1** [comment]
just an unrelated reference:
wu language ( https://github.com/wu-lang/wu ) which compiles to lua syntax has full static typing 
But here in erde I am asking for atleast type hints support

**Comment by bsuth** [comment]
closing this as a non-goal
