### ISSUE TITLE
Request for option to specify identifier for bitwise operations

### ISSUE THREAD

**Issue by wauterboi** [erde-lang/erde#38]
I am proposing a new option that causes bitwise operations to translate to method calls on a user-specified identifier.

> erde compile "file.erde" -t "jit" -bitwise_identifier "__BITOP"

This would place the burden of qualifying the identifier on the user, as all bitwise operators would compile to `_BITOP.<operator>`, i.e. `__BITOP.bor`. Here's an example use case:

> local __BITOP = require('my_bitwise_library');
> local x = 1 & 1;

This would translate to:

> local __BITOP = require('my_bitwise_library');
> local x = __BITOP(1, 1);

I can foresee design implications/tradeoffs/questions on an application-level by doing it this way, but I think this would provide greater support for custom environments that provide bitwise functions and eliminate the constant calls to `require`.

**Comment by bsuth** [comment]
> all bitwise operators would compile to `_BITOP.<operator>`, i.e. `__BITOP.bor`

Just to clarify from the example, `1 & 1` should translate to `__BITOP.band(1, 1)` right? (Currently its written as simply `__BITOP(1, 1)`).

I think this is already supported by the `--bitlib` flag but i could be misunderstanding?

**Comment by wauterboi** [comment]
I was under the impression that the way it works now is by repeatedly calling require to get the table belonging to the module. That's what the documentation led me to believe at least.

There are some global environments, like the one that comes with Garry's Mod, that has a library bundled in without the need for require. It has also mangled the require function, unfortunately. That's the motivation for this request.

**Comment by wauterboi** [comment]
Sorry for the accidental close - responded on mobile

**Comment by bsuth** [comment]
> I was under the impression that the way it works now is by repeatedly calling require to get the table belonging to the module. That's what the documentation led me to believe at least.
> 
> There are some global environments, like the one that comes with Garry's Mod, that has a library bundled in without the need for require. It has also mangled the require function, unfortunately. That's the motivation for this request.

ahh i see what you mean, yes you are right currently it does compile to a `require` statement.

I just tested both LuaJIT and Lua5.2, it seems like the `bit` and `bit32` libraries are already preloaded into the global scope anyways so actually the `require` isnt even needed for these cases, only for the case of a custom library.

It would be objectively more powerful to change the `--bitlib` flag to simply allow an expression instead of a library name and then remove the `require` call in the compiled code. For existing users with a custom library, `--bitlib "mybitlib"` would then become `--bitlib "require('mybitlib')"` and it would also cover your use case, although technically this is a breaking change. WDYT?

**Comment by wauterboi** [comment]
I think that sounds pretty great! I think maybe you could keep `--bitlib` as a deprecated flag and switch to a new flag name. Maybe you can use some suffixes like:
- `bitlibsource` or `bitlibsrc`
- `bitlibexpression` or `bitlibexpr`
- `bitlibvalue` or `bitlibval`

**Comment by bsuth** [comment]
That sounds good to me! That way the feature can be added immediately without waiting for a new "major version" while also giving users a notice :tada:

I'll see if I can work on this later this week, maybe the hardest part is thinking of a decent name :sweat_smile:
